HOSTS:
  centos-7-x64:
    platform: el-7-x86_64
    image: centos:7
    hypervisor: docker
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
CONFIG:
  type: aio
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] || 'puppet7' %>
